
services:
  web:
    build: .
    container_name: django_web
    environment:
      - DEBUG=1
      - DEBUG=True
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgres://postgres:12345@db_master:5432/django_chat_app
    depends_on:
      db_master:
        condition: service_healthy
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    command: ["bash", "-c", "python manage.py migrate && daphne django_chat_app.asgi:application --bind 0.0.0.0 --port 8000"]

  db_master:
    image: postgres:14
    container_name: db_master
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: django_chat_app
    volumes:
      - ./compose/postgres/master/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./compose/postgres/master/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./compose/postgres/master/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - db_master_data:/var/lib/postgresql/data  # Persist data
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  db_replica:
    image: postgres:14
    container_name: db_replica
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: django_chat_app
      PGPASSWORD: 12345
    depends_on:
      - web  # db_replica now depends on web, not db_master
    volumes:
      - ./compose/postgres/replica/replica-entrypoint.sh:/docker-entrypoint-initdb.d/replica-entrypoint.sh
      - ./compose/postgres/replica/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./compose/postgres/replica/wait-for-it.sh:/wait-for-it.sh
      - db_replica_data:/var/lib/postgresql/data  # Persist data
    command: ["bash", "-c", "/wait-for-it.sh db_master 5432 && /docker-entrypoint-initdb.d/replica-entrypoint.sh"]
    ports:
      - "5433:5432"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  # Celery worker
  # celery:
  #   build: .
  #   command: ["celery", "-A", "django_chat_app", "worker", "--loglevel=info", "--concurrency=4"]
  #   depends_on:
  #     - redis
  #   volumes:
  #     - .:/app

volumes:
  db_master_data:
  db_replica_data:
  static_volume:
  media_volume:
